name: Deploy React + Vite to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: yarn

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist